"""fix the null values error

Revision ID: 73cf1bfbd78c
Revises: cc5bc019867c
Create Date: 2024-07-08 21:48:55.063257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73cf1bfbd78c'
down_revision: Union[str, None] = 'cc5bc019867c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'updated_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=True)
    # # ### end Alembic commands ###
    
    # Perform the batch operation
    with op.batch_alter_table('users') as batch_op:
        # Alter the column to make it nullable
        batch_op.alter_column('updated_at',
                              existing_type=sa.DateTime,
                              nullable=True)


def downgrade() -> None:
    # # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'updated_at',
    #            existing_type=sa.DATETIME(),
    #            nullable=False)
    # # ### end Alembic commands ###
    
    # Reverse the batch operation for downgrade
    with op.batch_alter_table('users') as batch_op:
        # Revert the nullable change
        batch_op.alter_column('updated_at',
                              existing_type=sa.DateTime,
                              nullable=False)
